(* encode.ml
   Eunoia to LambdaPi encoding *)

module EO = Syntax_eo
open Api_lp

(* Overload management *)
let overload_counts : (string, int) Hashtbl.t =
  Hashtbl.create 32

let reset_overloads () =
  Hashtbl.clear overload_counts;
  reset_symbol_storage ()

(* Get a unique name for potentially overloaded symbols *)
let unique_name name =
  let escaped = esc name in
  match Hashtbl.find_opt overload_counts escaped with
  | None ->
    Hashtbl.add overload_counts escaped 1;
    escaped
  | Some n ->
    Hashtbl.replace overload_counts escaped (n + 1);
    Printf.sprintf "%s_%d" escaped n

let reset () =
  Api_lp.reset ();
  reset_overloads ()

(* Assumption stack for assume-push / step-pop scope handling *)
let assumption_stack : EO.term list ref = ref []
let push_assumption t = assumption_stack := t :: !assumption_stack
let pop_assumption () = match !assumption_stack with
  | t :: rest -> assumption_stack := rest; t
  | [] -> failwith "pop_assumption: empty stack"
let reset_assumptions () = assumption_stack := []
let assumption_stack_depth () = List.length !assumption_stack

(* ============================================================
   Elaboration interface — delegates to Elaborate module
   ============================================================ *)

module Elab = Elaborate

let set_signature = Elab.set_signature

(* ============================================================
   Prelude symbols and term builders
   ============================================================ *)

(* Prelude symbol accessors *)
let tau ()         = find "τ"
let arrow_sym ()   = find "⤳"
let dep_arrow_sym () = find "⤳d"
let app_sym ()     = find "APP"
let eo_type_sym () = find "{|eo::Type|}"
let eo_as_sym ()   = find "{|eo::as|}"

(* Symbol application with implicits *)
let rec count_leading_impl = function
  | true :: rest -> 1 + count_leading_impl rest
  | _ -> 0

let enc_sym s =
  let n = count_leading_impl s.Term.sym_impl in
  add_args (mk_Symb s) (List.init n (fun _ -> mk_Plac false))

(* Term builders *)
let tau_of t =
  mk_Appl (mk_Symb (tau ()), t)

let un_tau = function
  | Term.Appl (Term.Symb s, t) when s.Term.sym_name = "τ" -> t
  | t -> t

let hol_arrow t1 t2 =
  add_args (mk_Symb (arrow_sym ())) [t1; t2]

let hol_dep_arrow t1 f =
  add_args (mk_Symb (dep_arrow_sym ())) [t1; f]

let hol_app t1 t2 =
  add_args (enc_sym (app_sym ())) [t1; t2]

let eo_type () =
  mk_Symb (eo_type_sym ())

let eo_as t1 t2 =
  add_args (enc_sym (eo_as_sym ())) [t2; t1]

(* Strip eo::as from a resolved term tree: eo::as reduces to its second arg
   (rule eo::as _ $x ↪ $x), so it must not appear in rewrite rule LHS
   patterns where it would never match. *)
let strip_eo_as t =
  let eas = try Some (eo_as_sym ()) with _ -> None in
  let rec go t =
    match Core.Term.get_args t with
    | Core.Term.Symb s, [_ty; tm]
      when (match eas with Some e -> s == e | None -> false) ->
      go tm
    | _ ->
      match t with
      | Core.Term.Appl (t1, t2) -> Core.Term.mk_Appl (go t1, go t2)
      | _ -> t
  in
  go t

(* Integer encoding *)
let z0 ()    = find "Z0"
let zpos ()  = find "Zpos"
let zneg ()  = find "Zneg"
let pos_h () = find "H"
let pos_i () = find "I"
let pos_o () = find "O"

let rec enc_positive n =
  assert (n > 0);
  if n = 1 then mk_Symb (pos_h ())
  else
    let sym = if n mod 2 = 0 then pos_o () else pos_i () in
    mk_Appl (mk_Symb sym, enc_positive (n / 2))

let enc_int n =
  if n = 0 then mk_Symb (z0 ())
  else if n > 0 then mk_Appl (mk_Symb (zpos ()), enc_positive n)
  else mk_Appl (mk_Symb (zneg ()), enc_positive (-n))

let enc_rat num den =
  add_args (mk_Symb (find "Frac")) [enc_int num; enc_int den]

let ghost_sym name =
  let ghost_path = Sign.Ghost.path in
  match find_symbol_global name with
  | Some s when s.Term.sym_path = ghost_path -> s
  | _ ->
    let sym =
      Term.create_sym ghost_path
        Term.Public Term.Const Term.Eager false
        (Pos.none name) None mk_Kind []
    in
    Timed.(Sign.Ghost.sign.Sign.sign_symbols :=
      Lplib.Extra.StrMap.add name sym
        !(Sign.Ghost.sign.Sign.sign_symbols));
    sym

(* ============================================================
   Literal encoding
   ============================================================ *)

let enc_literal = function
  | Literal.Numeral n ->
    (* of_Z n — of_Z generated by enc_ltrl_num *)
    add_args (mk_Symb (find "of_Z")) [enc_int n]
  | Literal.Decimal d ->
    mk_Symb (ghost_sym (string_of_float d))
  | Literal.Rational (num, den) ->
    (* No Real type yet — encode as ghost symbol to allow rest of proof to proceed *)
    mk_Symb (ghost_sym (Printf.sprintf "%d/%d" num den))
  | Literal.String s ->
    (* No String type yet — encode as ghost symbol *)
    mk_Symb (ghost_sym (Printf.sprintf "\"%s\"" s))
  | Literal.Binary b ->
    let bits = String.sub b 2 (String.length b - 2) in
    let width = String.length bits in
    let value = int_of_string ("0b" ^ bits) in
    let mk_int n = add_args (mk_Symb (find "of_Z")) [enc_int n] in
    add_args
      (mk_Symb (find "{|@bv|}"))
      [mk_int value; mk_int width]
  | Literal.Hexadecimal h ->
    mk_Symb (ghost_sym h)

(* ============================================================
   Term encoding — consumes Elaborate.elab_term
   ============================================================ *)

(* Convenience: elaborate then encode *)
let rec enc_eo_term ps ctx t =
  enc_elab_term ctx (Elab.elab_term ps t)

(* Backward-compatible alias used by downstream functions *)
and enc_term ps ctx t = enc_eo_term ps ctx t

(* Encode an elaborated term into a LambdaPi Core.Term.
   No Eunoia signature lookups here — all decisions are in elab_term. *)
and enc_elab_term ctx (et : Elab.elab_term) : term =
  match et with
  | Elab.EType -> eo_type ()
  | Elab.ELit lit -> enc_literal lit
  | Elab.EVar s ->
    (match ctxt_find ctx (esc s) with
     | Some v -> mk_Vari v
     | None -> enc_sym (get_sym s))
  | Elab.ESym s ->
    (match ctxt_find ctx (esc s) with
     | Some v -> mk_Vari v
     | None -> enc_sym (get_sym s))
  | Elab.EAs (ty, tm) ->
    eo_as (enc_elab_term ctx ty) (enc_elab_term ctx tm)
  | Elab.EHolApp (head, args) ->
    let head' = enc_elab_term ctx head in
    List.fold_left hol_app head' (List.map (enc_elab_term ctx) args)
  | Elab.EBuiltinNary (s, ts) ->
    let ts' = List.map (enc_elab_term ctx) ts in
    let head = enc_sym (get_sym (esc s)) in
    List.fold_left (fun acc t -> add_args head [acc; t]) (List.hd ts') (List.tl ts')
  | Elab.EBuiltin (s, ts) ->
    let head = enc_sym (get_sym (esc s)) in
    add_args head (List.map (enc_elab_term ctx) ts)
  | Elab.EListCons args ->
    begin match args with
    | [x; xs] when not x.Elab.is_list && xs.Elab.is_list ->
      (* Two args where second is :list → direct cons *)
      add_args (enc_sym (get_sym (esc EO.Builtin.eo_list_cons)))
        [enc_elab_term ctx x.Elab.arg; enc_elab_term ctx xs.Elab.arg]
    | _ ->
      let nil = enc_sym (get_sym (esc EO.Builtin.eo_list_nil)) in
      List.fold_right (fun (ea : Elab.elab_arg) acc ->
        let t' = enc_elab_term ctx ea.Elab.arg in
        if ea.Elab.is_list then
          add_args (enc_sym (get_sym (esc EO.Builtin.eo_list_concat))) [t'; acc]
        else
          add_args (enc_sym (get_sym (esc EO.Builtin.eo_list_cons))) [t'; acc]
      ) args nil
    end
  | Elab.EApp (s, ts) ->
    let head = enc_sym (get_sym s) in
    add_args head (List.map (enc_elab_term ctx) ts)
  | Elab.ENary (info, _rest_annotated) ->
    enc_nary_from_elab ctx info
  | Elab.EArrow segs ->
    enc_arrow_segs ctx segs
  | Elab.EBinder info ->
    let cons' = enc_elab_term ctx info.Elab.cons_term in
    let body' = enc_elab_term ctx info.Elab.body in
    let head = enc_sym (get_sym info.Elab.binder_head) in
    add_args head [cons'; body']
  | Elab.ELet (name, rhs, body) ->
    let rhs_enc = enc_elab_term ctx rhs in
    let ty = mk_Plac false in
    let v = new_var (esc name) in
    let ctx' = ctxt_add ctx v ty in
    let body_enc = enc_elab_term ctx' body in
    Core.Term.mk_LLet (ty, rhs_enc, bind_var v body_enc)
  | Elab.ETypeof info ->
    begin match info with
    | Elab.TypeofParam ty ->
      (* param type needs encoding through the EO path *)
      enc_eo_term [] ctx ty
    | Elab.TypeofFallback sym_elab ->
      let s_esc = match sym_elab with
        | Elab.EVar s | Elab.ESym s -> esc s
        | _ -> ""
      in
      (* Try LP context first *)
      (match List.find_opt (fun (v, _, _) -> base_name v = s_esc) ctx with
       | Some (_, ty, _) -> un_tau ty
       | None ->
         add_args
           (enc_sym (get_sym "{|eo::typeof|}"))
           [enc_elab_term ctx sym_elab])
    end

(* Encode an ENary application from elaborated nary_info *)
and enc_nary_from_elab ctx (info : Elab.nary_info) =
  let head_sym = enc_sym (get_sym info.Elab.head) in
  let head =
    if info.Elab.opaque_args = [] then head_sym
    else add_args head_sym (List.map (enc_elab_term ctx) info.Elab.opaque_args)
  in
  let rest = info.Elab.rest_args in
  let rest_enc = List.map (fun (ea : Elab.elab_arg) -> enc_elab_term ctx ea.Elab.arg) rest in
  (* glue: either HOL app or list_concat for :list params *)
  let glue (ea : Elab.elab_arg) t_enc acc =
    if ea.Elab.is_list then
      add_args (enc_sym (get_sym (esc EO.Builtin.eo_list_concat_old))) [head; t_enc; acc]
    else
      hol_app (hol_app head t_enc) acc
  in
  let glue_rev acc (ea : Elab.elab_arg) t_enc =
    glue ea t_enc acc
  in
  let chop xs =
    let n = List.length xs in
    (List.filteri (fun i _ -> i < n - 1) xs, List.nth xs (n - 1))
  in
  match info.Elab.fold with
  | Elab.FoldNone ->
    List.fold_left hol_app head rest_enc

  | Elab.FoldRightNil nil_elab ->
    begin match nil_elab with
    | Elab.EVar "__last_is_list__" ->
      (* Last arg is :list — use it as accumulator *)
      let init_rest, last_rest = chop rest in
      let init_enc, last_enc = chop rest_enc in
      List.fold_right2 glue init_rest init_enc last_enc
    | _ ->
      let nil_enc = enc_elab_term ctx nil_elab in
      List.fold_right2 glue rest rest_enc nil_enc
    end

  | Elab.FoldLeftNil nil_elab ->
    begin match nil_elab with
    | Elab.EVar "__first_is_list__" ->
      (* First arg is :list — use it as initial accumulator *)
      List.fold_left2 glue_rev (List.hd rest_enc) (List.tl rest) (List.tl rest_enc)
    | _ ->
      let nil_enc = enc_elab_term ctx nil_elab in
      List.fold_left2 glue_rev nil_enc rest rest_enc
    end

  | Elab.FoldRight ->
    let init_rest, last_rest = chop rest in
    let init_enc, last_enc = chop rest_enc in
    List.fold_right2 glue init_rest init_enc last_enc

  | Elab.FoldLeft ->
    List.fold_left2 glue_rev (List.hd rest_enc) (List.tl rest) (List.tl rest_enc)

  | Elab.FoldChainable (op, orig_ts, ps) ->
    (* Generate pairs and re-encode via the combining operator *)
    let s = info.Elab.head in
    let rec aux = function
      | v :: w :: vs ->
        (EO.app_ho_list (EO.Symbol s) [v; w]) :: aux (w :: vs)
      | _ -> []
    in
    (* Re-elaborate and encode the generated EO term *)
    enc_eo_term ps ctx (EO.Apply (op, aux orig_ts))

  | Elab.FoldPairwise (op, orig_ts, ps) ->
    let s = info.Elab.head in
    let rec aux = function
      | v :: vs ->
        List.append
          (List.map (fun w -> EO.app_ho_list (EO.Symbol s) [v; w]) vs)
          (aux vs)
      | [] -> []
    in
    enc_eo_term ps ctx (EO.Apply (op, aux orig_ts))

  | Elab.FoldArgList (cons_name, orig_ts, ps) ->
    let list_term = EO.Apply (cons_name, orig_ts) in
    let list_enc = enc_eo_term ps ctx list_term in
    hol_app head list_enc

  | Elab.FoldRightNilNSN nil_elab ->
    let nil_enc = enc_elab_term ctx nil_elab in
    List.fold_right2 glue rest rest_enc nil_enc

  | Elab.FoldLeftNilNSN nil_elab ->
    let nil_enc = enc_elab_term ctx nil_elab in
    List.fold_left2 glue_rev nil_enc rest rest_enc

  | Elab.FoldRightNSN nil_elab ->
    let nil_enc = enc_elab_term ctx nil_elab in
    List.fold_right2 glue rest rest_enc nil_enc

  | Elab.FoldLeftNSN nil_elab ->
    let nil_enc = enc_elab_term ctx nil_elab in
    List.fold_left2 glue_rev nil_enc rest rest_enc

(* Encode arrow type segments from elaboration *)
and enc_arrow_segs ctx = function
  | [] -> fail "Empty arrow type"
  | [Elab.AResult t] ->
    enc_elab_term ctx t
  | Elab.ADepVar (s, eo_ty_elab, _) :: rest ->
    let s_esc = esc s in
    let eo_ty = enc_elab_term ctx eo_ty_elab in
    let type_of_s = tau_of eo_ty in
    let v = new_var s_esc in
    let ctx' = ctxt_add ctx v type_of_s in
    let body = enc_arrow_segs ctx' rest in
    let lam = mk_Abst (type_of_s, bind_var v body) in
    hol_dep_arrow eo_ty lam
  | Elab.ADepQuote s :: rest ->
    let s_esc = esc s in
    let type_of_s =
      match List.find_opt (fun (v, _, _) -> base_name v = s_esc) ctx with
      | Some (_, ty, _) -> ty
      | None ->
        let ctx_vars = List.map (fun (v, _, _) -> base_name v) ctx in
        failf "enc_arrow: variable `%s` not in context. Available: [%s]"
          s (String.concat ", " ctx_vars)
    in
    let eo_type_of_s = un_tau type_of_s in
    let v = new_var s_esc in
    let ctx' = ctxt_add ctx v type_of_s in
    let body = enc_arrow_segs ctx' rest in
    let lam = mk_Abst (type_of_s, bind_var v body) in
    hol_dep_arrow eo_type_of_s lam
  | Elab.APlain t :: rest ->
    hol_arrow (enc_elab_term ctx t) (enc_arrow_segs ctx rest)
  | Elab.AResult t :: rest ->
    (* AResult in non-final position — treat as plain *)
    hol_arrow (enc_elab_term ctx t) (enc_arrow_segs ctx rest)

(* Parameter encoding *)
let enc_params ps =
  let ctx, impl =
    List.fold_left
      (fun (ctx, acc) (str, ty, atts) ->
         let v = new_var (esc str) in
         (* Type parameters (T : Type) have type Set (= τ {|eo::Type|}) *)
         let ty' = tau_of (enc_term [] ctx ty) in
         let ctx' = ctxt_add ctx v ty' in
         let is_impl = List.mem EO.Implicit atts in
         (ctx', is_impl :: acc))
      (empty_ctxt, [])
      ps
  in
  (* Context is built in reverse order (ctxt_add prepends), which is what
     ctxt_to_prod/ctxt_to_abst expect (they use fold_left, wrapping first
     element as innermost binder, producing Π p_n. ... Π p_1. body).

     impl is accumulated in reverse order [p_n_impl; ...; p_1_impl], but
     the final type has params in original order (p_1 outermost), so we
     must reverse impl to match: [p_1_impl; ...; p_n_impl]. *)
  (ctx, List.rev impl)

(* Constant encoding *)
type enc_result = {
  syms  : sym list;
  rules : (sym * rule) list;
}

let empty_result = { syms = []; rules = [] }

(* Convert variables in a term to pattern variables.
   Takes a context (from enc_params) and replaces Vari nodes with Patt nodes.
   Variables not in ctx are replaced with wildcards. *)
let bind_pvars ctx full_ctx term =
  (* Build mapping from variable name to index for pattern vars *)
  let var_indices =
    List.mapi (fun i (v, _, _) -> (base_name v, i)) ctx
    |> List.rev  (* ctx is reversed, so reverse to get original order *)
  in
  (* Also track all variables from full_ctx that should become wildcards *)
  let full_names =
    List.map (fun (v, _, _) -> base_name v) full_ctx
    |> List.sort_uniq String.compare
  in
  let rec go = function
    | Core.Term.Vari v ->
      let name = base_name v in
      (match List.find_opt (fun (n, _) -> n = name) var_indices with
       | Some (_, idx) -> mk_Patt (Some idx, name, [||])
       | None ->
         (* If it's a variable from full_ctx but not in ctx, use wildcard *)
         if List.mem name full_names then mk_Plac false
         else mk_Vari v)
    | Core.Term.Symb s ->
      let name = s.Core.Term.sym_name in
      (match List.find_opt (fun (n, _) -> n = name) var_indices with
       | Some (_, idx) -> mk_Patt (Some idx, name, [||])
       | None ->
         (* If it's a name from full_ctx but not in ctx, use wildcard *)
         if List.mem name full_names then mk_Plac false
         else mk_Symb s)
    | Core.Term.Meta (m, ts) ->
      (match Timed.(!(m.Core.Term.meta_value)) with
       | None ->
         (* Unsolved meta: convert to wildcard *)
         mk_Plac false
       | Some mb ->
         (* Solved meta: unfold to its value and recurse *)
         go (Core.Term.msubst mb ts))
    | Core.Term.Appl (t1, t2) ->
      mk_Appl (go t1, go t2)
    | Core.Term.Abst (ty, b) ->
      let v, body = unbind b in
      mk_Abst (go ty, bind_var v (go body))
    | Core.Term.Prod (ty, b) ->
      let v, body = unbind b in
      mk_Prod (go ty, bind_var v (go body))
    | Core.Term.LLet (ty, t, b) ->
      let v, body = unbind b in
      Core.Term.mk_LLet (go ty, go t, bind_var v (go body))
    | t -> t
  in
  go term

let enc_decl str ps ty attr =
  let ctx, impl = enc_params ps in
  let body_ty = tau_of (enc_term [] ctx ty) in
  let body_ty = resolve_term ~ctx body_ty in
  let ty', _ = ctxt_to_prod ctx body_ty in
  let sym = add_constant ~impl (unique_name str) ty' in
  (* Generate eo::nil rule for operators with nil terminators.
     E.g., (declare-const and (-> Bool Bool Bool) :right-assoc-nil true)
     generates: rule {|eo::nil|} and Bool ↪ true; *)
  let nil_term_opt = match attr with
    | Some (EO.RightAssocNil t)    -> Some t
    | Some (EO.LeftAssocNil t)     -> Some t
    | Some (EO.RightAssocNilNSN t) -> Some t
    | Some (EO.LeftAssocNilNSN t)  -> Some t
    | _ -> None
  in
  let nil_rules = match nil_term_opt with
    | None -> []
    | Some nil_eo_term ->
      (* Extract return type from arrow: (-> T1 ... Tn) → Tn *)
      let ret_type_eo = match ty with
        | EO.Apply ("->", ts) when ts <> [] ->
          List.nth ts (List.length ts - 1)
        | _ -> ty
      in
      let eo_nil_sym = get_sym (esc "eo::nil") in
      let op_enc = mk_Symb sym in
      let ret_type_enc = enc_term [] empty_ctxt ret_type_eo in
      let nil_enc = enc_term [] empty_ctxt nil_eo_term in
      (* eo::nil has signature: [T1] [T2] (f : τ (T1 ⤳ T2 ⤳ T2)) (T : Set)
         Use placeholders for the implicit T1, T2 args *)
      let rule : rule = {
        lhs = [mk_Plac false; mk_Plac false; op_enc; ret_type_enc];
        rhs = nil_enc;
        arity = 4;
        arities = [||];
        vars_nb = 0;
        xvars_nb = 0;
        names = [||];
        rule_pos = None;
      } in
      [(eo_nil_sym, rule)]
  in
  { syms = [sym]; rules = nil_rules; }

(* Check if an Eunoia AST term contains eo::requires *)
let rec has_eo_requires = function
  | EO.Apply (s, _) when s = EO.Builtin.eo_requires -> true
  | EO.Apply (_, args) -> List.exists has_eo_requires args
  | EO.Bind (_, _, body) -> has_eo_requires body
  | _ -> false

let enc_defn str ps tm ty_opt =
  match ps with
  | [] ->
    (* Nullary defines are expanded by the elaborator — nothing to encode *)
    empty_result
  | _ ->
    let ctx, impl = enc_params ps in
    let body_raw = enc_term ps ctx tm in
    let expected_ty = Option.map (fun ty -> tau_of (enc_term ps ctx ty)) ty_opt in
    let body = resolve_term ~ctx ?expected_ty body_raw in
    (* When the body contains eo::requires (which constrains type params,
       causing the inferred body type to differ from the parametric type),
       encode as a sequential symbol + rule instead of a definition.
       This preserves the parametric return type (e.g., τ T instead of
       τ (?? ... Int Real)), which is needed for downstream type checking. *)
    let has_type_param =
      List.exists (fun (_, ty, _) -> ty = EO.Symbol EO.Builtin.ty_type) ps
    in
    if has_eo_requires tm && has_type_param then begin
      (* For defines with eo::requires and type params, encode as a
         sequential symbol + rule to preserve the parametric return type
         (LP's inference would over-specialize due to eo::requires).
         Infer return type: use last param's type if concrete, else first
         Type parameter. *)
      let return_ty_enc =
        (* Check if the last parameter has a concrete (non-type-variable) type *)
        let last_param_ty = match List.rev ps with
          | (_, ty, _) :: _ ->
            let is_type_param name =
              List.exists (fun (n, t, _) -> n = name && t = EO.Symbol EO.Builtin.ty_type) ps
            in
            (match ty with
             | EO.Symbol s when is_type_param s -> None  (* type variable *)
             | _ -> Some ty)  (* concrete type like Bool, Int, etc. *)
          | [] -> None
        in
        match last_param_ty with
        | Some ret_ty -> tau_of (enc_term ps ctx ret_ty)
        | None ->
          (* Fallback: use first Type parameter *)
          let type_param_name =
            List.find_map (fun (name, ty, _) ->
              if ty = EO.Symbol EO.Builtin.ty_type then Some (esc name) else None) ps
          in
          match type_param_name with
          | Some name ->
            (match List.find_map (fun (v, _, _) ->
                     if Core.Term.base_name v = name then Some v else None)
                     (List.rev ctx) with
             | Some tv -> tau_of (mk_Vari tv)
             | None -> tau_of (mk_Plac false))
          | None -> tau_of (mk_Plac false)
      in
      begin match return_ty_enc with
      | body_ty ->
        let body_ty = resolve_term ~ctx body_ty in
        let ty, _ = Core.Ctxt.to_prod ctx body_ty in
        let sym = add_sequential ~impl (unique_name str) ty in
        (* Build rule: sym $x1 ... $xn ↪ body *)
        let names = List.rev_map (fun (v, _, _) -> base_name v) ctx
                    |> Array.of_list in
        let vars_nb = List.length ctx in
        let lhs_args =
          let n = List.length ctx in
          List.mapi (fun i (v, _, _) ->
            mk_Patt (Some (n - 1 - i), base_name v, [||])) (List.rev ctx)
        in
        let rhs = bind_pvars ctx ctx body in
        let rule : rule = {
          lhs = lhs_args;
          rhs;
          arity = List.length lhs_args;
          arities = Array.make vars_nb 0;
          vars_nb;
          xvars_nb = 0;
          names;
          rule_pos = None;
        } in
        { syms = [sym]; rules = [(sym, rule)]; }
      end
    end else begin
      let tm' = ctxt_to_abst ctx body in
      { syms = [add_definition ~impl (unique_name str) None tm'];
        rules = []; }
    end

(* Rule encoding for programs *)

(* Encode a program case as a rewrite rule *)
(* Coerce a term of type τ int to τ T by wrapping with of_Z T.
   This is needed because Eunoia builtins like eo::len return raw integers
   (τ int = ℤ), but their results may be used where the declared numeral
   literal type (e.g. Int) is expected. *)
let coerce_int_to_lit ctx term expected_ty =
  let prob = Core.Term.new_problem () in
  match Core.Infer.infer_noexn prob ctx term with
  | Some (_, inferred_ty) ->
    let inner_inferred = un_tau inferred_ty in
    let inner_expected = un_tau expected_ty in
    let is_int_sym = function
      | Core.Term.Symb s -> s.Core.Term.sym_name = "int"
      | _ -> false
    in
    if is_int_sym inner_inferred && not (is_int_sym inner_expected) then
      (* Wrap: of_Z term — of_Z : τ (int ⤳ T) *)
      (try
        let of_z = find "of_Z" in
        mk_Appl (mk_Symb of_z, term)
      with _ -> term)
    else term
  | None -> term

let enc_case eo_ps ctx impl_ctx sym ?(wildcard_impl_vars=false) ?expected_ty (t1, t2 : EO.term * EO.term) =

  let enc_rhs t =
    let encoded = enc_term eo_ps ctx t |> resolve_term ~debug:!verbose ~ctx in
    let coerced = match expected_ty with
      | Some exp_ty -> coerce_int_to_lit ctx encoded exp_ty
      | None -> encoded
    in
    coerced |> bind_pvars ctx ctx
  in

  (* For the LHS, resolve_term infers the implicit args from the explicit
     pattern args. We keep the resolved implicit args when they are fully
     resolved (e.g., Seq $U instead of bare $T when the pattern refines
     the type). When resolution leaves unsolved metas, we fall back to the
     impl_ctx variable to ensure pattern variables are bound in the LHS. *)
  let enc_lhs t =
    let encoded = enc_term eo_ps ctx t in
    let resolved = resolve_term ~debug:!verbose ~ctx encoded in
    let resolved = strip_eo_as resolved in
    let head, args = Core.Term.get_args resolved in
    let is_our_sym = match head with
      | Core.Term.Symb s -> s == sym
      | _ -> false
    in
    if is_our_sym then begin
      let n_impl = List.length impl_ctx in
      let resolved_impl = if n_impl <= List.length args
        then List.filteri (fun i _ -> i < n_impl) args
        else []
      in
      let explicit_args = if n_impl <= List.length args
        then List.filteri (fun i _ -> i >= n_impl) args
        else args
      in
      (* For each implicit arg: use the resolved version if it has no
         unsolved metas, otherwise fall back to the impl_ctx variable. *)
      let impl_vars = List.rev_map (fun (v, _, _) -> mk_Vari v) impl_ctx in
      let is_impl_var t =
        if not wildcard_impl_vars then false
        else
          (* Unfold solved metas to check the underlying value *)
          let t' = match t with
            | Core.Term.Meta (m, ts) ->
              (match Timed.(!(m.Core.Term.meta_value)) with
               | Some mb -> Core.Term.msubst mb ts
               | None -> t)
            | _ -> t
          in
          match t' with
          | Core.Term.Vari v ->
            List.exists (fun (iv, _, _) ->
              Core.Term.eq_vars v iv) impl_ctx
          | _ -> false
      in
      let impl_args = List.map2 (fun resolved_arg _fallback ->
        if has_unsolved_metas resolved_arg || is_impl_var resolved_arg
        then mk_Plac false
        else resolved_arg
      ) resolved_impl impl_vars in
      (* Apply nonvar_metas_to_plac selectively: only to args that
         contain Stdlib.Z's int or unsolved metas. *)
      let cleanup_if_needed t =
        if has_unsolved_metas t || Api_lp.has_stdlib_int t
        then Api_lp.nonvar_metas_to_plac t
        else t
      in
      let final_impl = List.map cleanup_if_needed impl_args in
      let final_explicit = List.map cleanup_if_needed explicit_args in
      let new_args = final_impl @ final_explicit in
      bind_pvars ctx ctx (add_args (mk_Symb sym) new_args)
    end else
      bind_pvars ctx ctx resolved
  in

  let l, rhs = enc_lhs t1, enc_rhs t2 in
  let _,lhs = Core.Term.get_args l in
  let names = List.rev_map (fun (v, _, _) -> base_name v) ctx |> Array.of_list in
  let vars_nb = List.length ctx in
  let rule : rule = {
    lhs;
    rhs;
    arity = List.length lhs;
    arities = Array.make vars_nb 0;
    vars_nb;
    xvars_nb = 0;
    names;
    rule_pos = None;
  } in
  (sym, rule)

(* Deduplicate while preserving order of first occurrence *)
let dedup_params ps =
  let seen = Hashtbl.create (List.length ps) in
  List.filter (fun (name, _, _) ->
    if Hashtbl.mem seen name then false
    else (Hashtbl.add seen name (); true))
  ps

let enc_prog str ps doms ran cases =
  let ctx, _ = enc_params ps in
  let ty_raw = EO.Apply (EO.Builtin.ty_arrow, doms @ [ran]) in
  let body_ty_raw = tau_of (enc_term ps ctx ty_raw) in
  let body_ty = resolve_term ~ctx body_ty_raw in
  (* Variables from ctx that are free in the type become implicit params *)
  let free_vars = Api_lp.LibTerm.free_vars body_ty in
  let impl_ctx =
    List.filter (fun (v, _, _) -> Core.Term.VarSet.mem v free_vars) ctx
  in
  let impl = List.map (fun _ -> true) impl_ctx in
  let ty, _ = Core.Ctxt.to_prod impl_ctx body_ty in
  (* If the symbol already exists (forward declaration), reuse it
     and only encode the rules — no new symbol declaration. *)
  let escaped = esc str in
  let existing = Api_lp.find_symbol escaped in
  let sym = match existing with
    | Some s -> s
    | None   -> add_sequential ~impl (unique_name str) ty
  in
  (* Detect programs with both Int and Real param types: these need
     wildcard implicits to avoid type preservation failures with
     non-reducible type union functions like $arith_typeunion *)
  let wildcard_impl_vars =
    let param_types = List.map (fun (_, ty, _) -> ty) ps in
    let has t = List.exists (fun ty -> ty = t) param_types in
    has (EO.Symbol "Int") && has (EO.Symbol "Real")  (* CPC-specific names, not builtins *)
  in
  (* Compute expected type for RHS: τ(range) *)
  let rhs_expected_ty = tau_of (enc_term ps ctx ran) in
  let _n_cases = List.length cases in
  let rules =
    List.map (fun (lhs, rhs) ->
      enc_case ps ctx impl_ctx sym ~wildcard_impl_vars ~expected_ty:rhs_expected_ty (lhs, rhs))
    cases
  in
  (* Forward-declared symbol: return no syms so the declaration is
     not printed again.  The rules appear at this position in the
     output since each enc_result is printed in order. *)
  match existing with
  | Some _ -> { syms = []; rules; }
  | None   -> { syms = [sym]; rules; }

(* Create a simple rule with no pattern variables: sym arg1 arg2 ... ↪ rhs *)
let make_rule sym lhs rhs =
  let rule : rule = {
    lhs;
    rhs;
    arity = List.length lhs;
    arities = [||];
    vars_nb = 0;
    xvars_nb = 0;
    names = [||];
    rule_pos = None;
  } in
  (sym, rule)

(* Generate numeral literal infrastructure: of_Z, eo:: arithmetic symbols,
   and their computation rules.
   Called when processing declare-consts <numeral> Int.
   All arithmetic symbols are generated here as non-polymorphic,
   Int-specialized symbols. *)
let enc_ltrl_num target =
  (* target = the CPC type, e.g. Int *)
  let int_set = mk_Symb (get_sym "int") in
  (* of_Z : τ (int ⤳ Int)  —  coercion from Stdlib int to CPC Int *)
  let of_z_ty = tau_of (hol_arrow int_set target) in
  let of_z_sym = add_constant "of_Z" of_z_ty in
  (* Stdlib symbols for computation rules *)
  let stdlib_add = get_sym "+" in   (* ℤ → ℤ → ℤ *)
  let stdlib_mul = get_sym "*" in   (* ℤ → ℤ → ℤ *)
  let stdlib_neg = get_sym "—" in   (* ℤ → ℤ *)
  let stdlib_isZneg = get_sym "isZneg" in (* ℤ → 𝔹 *)
  let stdlib_isGt = get_sym "isGt" in     (* Comp → 𝔹 *)
  let stdlib_cmp = get_sym "≐" in         (* ℤ → ℤ → Comp *)
  let bool_target = mk_Symb (find "Bool") in
  (* Helper: build a rule *)
  let mk_rl sym lhs rhs nvars =
    let rule : rule = {
      lhs; rhs;
      arity = List.length lhs; arities = [||];
      vars_nb = nvars; xvars_nb = 0;
      names = [||]; rule_pos = None;
    } in (sym, rule)
  in
  let p i name = mk_Patt (Some i, name, [||]) in
  let of_z t = mk_Appl (mk_Symb of_z_sym, t) in
  (* {|eo::add|} : τ (Int ⤳ Int ⤳ Int)
     rule {|eo::add|} (of_Z $i) (of_Z $j) ↪ of_Z ($i + $j) *)
  let add_ty = tau_of (hol_arrow target (hol_arrow target target)) in
  let add_sym = add_sequential "{|eo::add|}" add_ty in
  let add_rule_ = mk_rl add_sym
    [of_z (p 0 "i"); of_z (p 1 "j")]
    (of_z (add_args (mk_Symb stdlib_add) [p 0 "i"; p 1 "j"]))
    2 in
  (* {|eo::mul|} : τ (Int ⤳ Int ⤳ Int)
     rule {|eo::mul|} (of_Z $i) (of_Z $j) ↪ of_Z ($i * $j) *)
  let mul_ty = tau_of (hol_arrow target (hol_arrow target target)) in
  let mul_sym = add_sequential "{|eo::mul|}" mul_ty in
  let mul_rule = mk_rl mul_sym
    [of_z (p 0 "i"); of_z (p 1 "j")]
    (of_z (add_args (mk_Symb stdlib_mul) [p 0 "i"; p 1 "j"]))
    2 in
  (* {|eo::neg|} : τ (Int ⤳ Int)
     rule {|eo::neg|} (of_Z $i) ↪ of_Z (— $i) *)
  let neg_ty = tau_of (hol_arrow target target) in
  let neg_sym = add_sequential "{|eo::neg|}" neg_ty in
  let neg_rule = mk_rl neg_sym
    [of_z (p 0 "i")]
    (of_z (mk_Appl (mk_Symb stdlib_neg, p 0 "i")))
    1 in
  (* {|eo::is_neg|} : τ (Int ⤳ Bool)
     rule {|eo::is_neg|} (of_Z $i) ↪ isZneg $i *)
  let is_neg_ty = tau_of (hol_arrow target bool_target) in
  let is_neg_sym = add_sequential "{|eo::is_neg|}" is_neg_ty in
  let is_neg_rule = mk_rl is_neg_sym
    [of_z (p 0 "i")]
    (mk_Appl (mk_Symb stdlib_isZneg, p 0 "i"))
    1 in
  (* {|eo::gt|} : τ (Int ⤳ Int ⤳ Bool)
     rule {|eo::gt|} (of_Z $i) (of_Z $j) ↪ isGt ($i ≐ $j) *)
  let gt_ty = tau_of (hol_arrow target (hol_arrow target bool_target)) in
  let gt_sym = add_sequential "{|eo::gt|}" gt_ty in
  let gt_rule = mk_rl gt_sym
    [of_z (p 0 "i"); of_z (p 1 "j")]
    (mk_Appl (mk_Symb stdlib_isGt,
      add_args (mk_Symb stdlib_cmp) [p 0 "i"; p 1 "j"]))
    2 in
  (* {|eo::is_z|} [T : Set] : τ (T ⤳ Bool)
     rule {|eo::is_z|} [Int] (of_Z _) ↪ true *)
  let is_z_tv = new_var "T" in
  let is_z_inner_ty = tau_of (hol_arrow (mk_Vari is_z_tv) bool_target) in
  let set_ty = tau_of (mk_Symb (eo_type_sym ())) in
  let is_z_ty = mk_Prod (set_ty, bind_var is_z_tv is_z_inner_ty) in
  let is_z_sym = add_sequential ~impl:[true] "{|eo::is_z|}" is_z_ty in
  let true_sym = find "true" in
  let is_z_rule = mk_rl is_z_sym
    [target; of_z (p 0 "_")]
    (mk_Symb true_sym)
    1 in
  (* {|eo::to_z|} : τ (Int ⤳ Int)
     rule {|eo::to_z|} (of_Z $i) ↪ of_Z $i *)
  let to_z_ty = tau_of (hol_arrow target target) in
  let to_z_sym = add_sequential "{|eo::to_z|}" to_z_ty in
  let to_z_rule = mk_rl to_z_sym
    [of_z (p 0 "i")]
    (of_z (p 0 "i"))
    1 in
  (* {|eo::zdiv|} : τ (Int ⤳ Int ⤳ Int) — no computation rules *)
  let zdiv_ty = tau_of (hol_arrow target (hol_arrow target target)) in
  let zdiv_sym = add_sequential "{|eo::zdiv|}" zdiv_ty in
  (* {|eo::zmod|} : τ (Int ⤳ Int ⤳ Int) — no computation rules *)
  let zmod_ty = tau_of (hol_arrow target (hol_arrow target target)) in
  let zmod_sym = add_sequential "{|eo::zmod|}" zmod_ty in
  (* Integer-dependent list operations.
     These use of_Z-wrapped integers, so they must be generated here
     rather than in Prelude.lp which only has LP's builtin int. *)
  let set_ty = tau_of (mk_Symb (eo_type_sym ())) in
  let w = mk_Plac false in  (* wildcard for implicit args *)
  let app_s = app_sym () in
  (* APP t1 t2 — applies hol_app with implicit type placeholders *)
  let app t1 t2 = add_args (enc_sym app_s) [t1; t2] in
  let nil_sym = find "{|eo::nil|}" in
  let ite_sym = find "{|eo::ite|}" in
  let eq_sym = find "{|eo::eq|}" in
  let nil f t2 = add_args (enc_sym nil_sym) [f; t2] in
  let ite c t e = add_args (enc_sym ite_sym) [c; t; e] in
  let eq a b = add_args (enc_sym eq_sym) [a; b] in

  (* Build type: [T1 T2] (f : τ (T1 ⤳ T2 ⤳ T2)) : τ (... ) *)
  let mk_list_sym name impl_n inner_ty =
    (* inner_ty is built with fresh type variables;
       we wrap in Π [T1:Set] [T2:Set] (f : τ(T1⤳T2⤳T2)) → τ(inner) *)
    let tv2 = new_var "T2" in
    let tv1 = new_var "T1" in
    let f_ty_inner = hol_arrow (mk_Vari tv1) (hol_arrow (mk_Vari tv2) (mk_Vari tv2)) in
    let body = tau_of (hol_arrow f_ty_inner (inner_ty (mk_Vari tv1) (mk_Vari tv2))) in
    let ty = mk_Prod (set_ty, bind_var tv2 (mk_Prod (set_ty, bind_var tv1 body))) in
    let impl = List.init impl_n (fun _ -> true) in
    add_sequential ~impl name ty
  in

  (* {|eo::list_len|} [T1 T2] (f : τ(T1⤳T2⤳T2)) : τ(T2 ⤳ Int) *)
  let list_len_sym = mk_list_sym "{|eo::list_len|}" 2
    (fun _t1 t2 -> hol_arrow t2 target) in
  (* rule list_len $f (APP (APP $f $x) $xs) ↪ eo::add (list_len $f $xs) (of_Z 1)
     with list_len $f $x ↪ eo::ite (eo::eq $x (eo::nil $f _)) (of_Z 0) (of_Z 1) *)
  let list_len_r1 = mk_rl list_len_sym
    [w; w; p 0 "f"; app (app (p 0 "f") (p 1 "x")) (p 2 "xs")]
    (add_args (mk_Symb add_sym) [
      add_args (enc_sym list_len_sym) [p 0 "f"; p 2 "xs"];
      of_z (enc_int 1)])
    3 in
  let list_len_r2 = mk_rl list_len_sym
    [w; p 3 "T2"; p 0 "f"; p 1 "x"]
    (ite (eq (p 1 "x") (nil (p 0 "f") (p 3 "T2")))
         (of_z (enc_int 0)) (of_z (enc_int 1)))
    4 in

  (* {|eo::list_nth|} [T1 T2] (f : τ(T1⤳T2⤳T2)) : τ(T2 ⤳ Int ⤳ T1) *)
  let list_nth_sym = mk_list_sym "{|eo::list_nth|}" 2
    (fun t1 t2 -> hol_arrow t2 (hol_arrow target t1)) in
  (* rule list_nth $f (APP (APP $f $x) $xs) (of_Z 0) ↪ $x
     with list_nth $f (APP (APP $f _) $xs) $i ↪ list_nth $f $xs (eo::add $i (of_Z -1)) *)
  let list_nth_r1 = mk_rl list_nth_sym
    [w; w; p 0 "f"; app (app (p 0 "f") (p 1 "x")) (p 2 "xs"); of_z (enc_int 0)]
    (p 1 "x")
    3 in
  let list_nth_r2 = mk_rl list_nth_sym
    [w; w; p 0 "f"; app (app (p 0 "f") (p 1 "_")) (p 2 "xs"); p 3 "i"]
    (add_args (enc_sym list_nth_sym) [p 0 "f"; p 2 "xs";
      add_args (mk_Symb add_sym) [p 3 "i"; of_z (enc_int (-1))]])
    4 in

  (* list_find_aux [T1 T2] (f : τ(T1⤳T2⤳T2)) : τ(T1 ⤳ T2 ⤳ Int ⤳ Int) *)
  let find_aux_sym = mk_list_sym "list_find_aux" 2
    (fun t1 t2 -> hol_arrow t1 (hol_arrow t2 (hol_arrow target target))) in
  (* rule find_aux $f $x (APP (APP $f $y) $ys) $i
       ↪ eo::ite (eo::eq $x $y) $i (find_aux $f $x $ys (eo::add $i (of_Z 1)))
     with find_aux $f $x $xs $i
       ↪ eo::ite (eo::eq $xs (eo::nil $f _)) (of_Z -1) (eo::ite (eo::eq $x $xs) $i (of_Z -1)) *)
  let find_aux_r1 = mk_rl find_aux_sym
    [w; w; p 0 "f"; p 1 "x"; app (app (p 0 "f") (p 2 "y")) (p 3 "ys"); p 4 "i"]
    (ite (eq (p 1 "x") (p 2 "y")) (p 4 "i")
      (add_args (enc_sym find_aux_sym) [p 0 "f"; p 1 "x"; p 3 "ys";
        add_args (mk_Symb add_sym) [p 4 "i"; of_z (enc_int 1)]]))
    5 in
  let find_aux_r2 = mk_rl find_aux_sym
    [w; p 5 "T2"; p 0 "f"; p 1 "x"; p 2 "xs"; p 3 "i"]
    (ite (eq (p 2 "xs") (nil (p 0 "f") (p 5 "T2")))
         (of_z (enc_int (-1)))
         (ite (eq (p 1 "x") (p 2 "xs")) (p 3 "i") (of_z (enc_int (-1)))))
    6 in

  (* {|eo::list_find|} [T1 T2] (f : τ(T1⤳T2⤳T2)) : τ(T2 ⤳ T1 ⤳ Int) *)
  let list_find_sym = mk_list_sym "{|eo::list_find|}" 2
    (fun t1 t2 -> hol_arrow t2 (hol_arrow t1 target)) in
  (* rule list_find $f $xs $x ↪ find_aux $f $x $xs (of_Z 0) *)
  let list_find_r1 = mk_rl list_find_sym
    [w; w; p 0 "f"; p 1 "xs"; p 2 "x"]
    (add_args (enc_sym find_aux_sym) [p 0 "f"; p 2 "x"; p 1 "xs"; of_z (enc_int 0)])
    3 in

  { syms = [of_z_sym; add_sym; mul_sym; neg_sym;
            is_neg_sym; gt_sym; is_z_sym; to_z_sym;
            zdiv_sym; zmod_sym;
            list_len_sym; list_nth_sym; find_aux_sym; list_find_sym];
    rules = [add_rule_; mul_rule; neg_rule;
             is_neg_rule; gt_rule; is_z_rule; to_z_rule;
             list_len_r1; list_len_r2;
             list_nth_r1; list_nth_r2;
             find_aux_r1; find_aux_r2;
             list_find_r1]; }

let enc_ltrl cat ty =
  EO.set_lit_type cat ty;
  EO.register_lit_alias cat ty;
  let target = enc_term [] empty_ctxt ty in
  match cat with
  | Literal.STR ->
    (* String type not fully supported — register alias but produce no symbols *)
    register_alias "{|eo::String|}" target;
    empty_result
  | Literal.NUM ->
    register_alias "{|eo::Int|}" target;
    enc_ltrl_num target
  | _ ->
    failf "enc_ltrl: unsupported literal category %s"
      (Literal.lit_category_str cat)

(* Rule encoding for declare-rule *)

(* Get the Proof symbol from prelude *)
let proof_sym () = find "Proof"

(* Build Proof(t) application *)
let mk_proof t = mk_Appl (mk_Symb (proof_sym ()), t)

(* Encode a declare-rule.

   For rules with :args, we generate:

     symbol <name>_aux [<type_params>] : τ T1 → ... → τ Tn → TYPE;
     rule <name>_aux <pattern1> ... <patternN>
       ↪ Proof <prem1> → ... → Proof <premM> → Proof <conclusion>;

     symbol <name> [<type_params>] :
       Π x1 : τ T1, ... Π xn : τ Tn, <name>_aux x1 ... xn;

   For rules without :args (only :premises), we generate:

     symbol <name> [<type_params>] (p1 : τ T1) ... :
       Proof <prem1> → ... → Proof <premM> → Proof <conclusion>;
*)
let enc_rule str ps (rdec : EO.rule_dec) =
  (* :assumption F — the assumption variable should be explicit in the LP type,
     since LP can't infer it. We add it to the args so it's treated as explicit. *)
  let assm_names = match rdec.assm with
    | Some (EO.Symbol s) -> [esc s]
    | _ -> []
  in
  (* Ignore reqs for now - should wrap conclusion in eo::requires *)
  let _ = rdec.reqs in

  (* For :premise-list rules, add the premise-list pattern as an arg
     so it goes through the _aux pattern-matching path. The premise
     becomes Proof E where E is the folded formula. *)
  let args, prems, is_premise_list, n_explicit_args = match rdec.prem with
    | None -> (rdec.args, [], false, List.length rdec.args)
    | Some (EO.Simple ts) -> (rdec.args, ts, false, List.length rdec.args)
    | Some (EO.PremiseList (pattern, _op)) ->
      (* Add the pattern as the first arg — enc_step passes formula_args
         (the folded premise formula) before :args, so the LP type must
         bind the premise-list variable first to match. *)
      ([pattern] @ rdec.args, [pattern], true, List.length rdec.args)
  in

  let conc = match rdec.conc with
    | EO.Conclusion t | EO.ConclusionExplicit t -> t
  in

  let ctx, _ = enc_params ps in

  (* Helper: build Proof p1 → Proof p2 → ... → Proof conclusion *)
  let build_proof_arrow prems conc_term =
    let conc_proof = mk_proof conc_term in
    List.fold_right
      (fun prem acc ->
         let prem_proof = mk_proof prem in
         mk_Prod (prem_proof, bind_var (new_var "_") acc))
      prems conc_proof
  in

  (* Check if an arg is a simple variable reference (not a pattern) *)
  let is_simple_arg = function
    | EO.Symbol s -> EO.prm_mem s ps  (* It's a parameter reference *)
    | _ -> false
  in

  (* Check if ALL args are simple variable references *)
  let all_args_simple = List.for_all is_simple_arg args in

  (* Premises and conclusions are formulas of type τ Bool.
     Passing this as expected_ty helps LambdaPi resolve polymorphic return types. *)
  let tau_bool = tau_of (mk_Symb (find "Bool")) in

  if args = [] || all_args_simple then begin
    (* No :args - simple rule with just premises and conclusion *)
    (* Encode premises and conclusion *)
    let prems_enc = List.map (fun p -> enc_term ps ctx p |> resolve_term ~debug:!verbose ~ctx ~expected_ty:tau_bool) prems in
    let conc_enc = enc_term ps ctx conc |> resolve_term ~debug:!verbose ~ctx ~expected_ty:tau_bool in

    (* If the conclusion has unsolved metas AND contains eo::ite (whose
       return type depends on an irreducible condition, preventing LambdaPi
       from re-inferring the types), replace unsolved metas with the first
       Set-typed variable from the context, and emit the symbol declaration
       as raw text with print_implicits=true to make the filled args visible. *)
    let rec has_eo_ite = function
      | Core.Term.Symb s -> s.Core.Term.sym_name = "{|eo::ite|}"
      | Core.Term.Appl (t1, t2) -> has_eo_ite t1 || has_eo_ite t2
      | _ -> false
    in
    let needs_explicit = Api_lp.has_unsolved_metas conc_enc && has_eo_ite conc_enc in
    let conc_enc, replacements =
      if needs_explicit then
        let type_vars = List.filter_map (fun (v, ty, _) ->
          match ty with
          | Core.Term.Appl (Core.Term.Symb s1, Core.Term.Symb s2)
            when s1.Core.Term.sym_name = "τ"
              && s2.Core.Term.sym_name = "{|eo::Type|}" -> Some v
          | _ -> None) ctx in
        match type_vars with
        | tv :: _ ->
          let solved = Api_lp.solve_set_metas_to conc_enc (mk_Vari tv) in
          (* Collect relation symbols that had unsolved metas filled *)
          let tv_name = Core.Term.base_name tv in
          let repls = ref [] in
          let rec find_relations = function
            | Core.Term.Appl _ as t ->
              let head, args = Core.Term.get_args t in
              (match head with
               | Core.Term.Symb s when
                 (let n = s.Core.Term.sym_name in
                  n = ">" || n = "<" || n = ">=" || n = "<=" || n = "=") &&
                 s.Core.Term.sym_impl <> [] ->
                 let n_impl = List.length s.Core.Term.sym_impl in
                 let impl_args = List.filteri (fun i _ -> i < n_impl) args in
                 let all_same_var = List.for_all (fun a ->
                   match a with
                   | Core.Term.Vari v -> Core.Term.base_name v = tv_name
                   | _ -> false) impl_args in
                 if all_same_var then
                   let impl_str = String.concat " " (List.map (fun _ -> tv_name) impl_args) in
                   repls := (s.Core.Term.sym_name, impl_str) :: !repls
               | _ -> ());
              List.iter find_relations args
            | _ -> ()
          in
          find_relations solved;
          (solved, !repls)
        | [] -> (conc_enc, [])
      else (conc_enc, [])
    in

    (* Build the body type in layers:
       1. Core: Proof conclusion
       2. Premises: Proof prem1 → ... → Proof premN → core
       3. Explicit args (:args, :assumption): bind as (x : τ T) → ...
       4. Implicit params: whatever is still free, bound as [x : τ T] → ... *)
    let core_ty = build_proof_arrow prems_enc conc_enc in

    (* Determine which params are explicit args *)
    let args_names = List.filter_map (function
      | EO.Symbol s -> Some (esc s)
      | _ -> None) args in
    let args_names = args_names @ assm_names in

    (* Bind explicit arg params around the core type.
       Order must match enc_step's application order, which is:
         formula_args @ args_enc @ prems_enc
       i.e. premise-list formula first (if any), then :args in order,
       then the proof.  to_prod wraps the first element as innermost
       binder, so we pass the *reverse* of the desired LP param order. *)
    let explicit_ctx =
      let ctx_by_name = List.map (fun ((v, _, _) as entry) ->
        (base_name v, entry)) ctx in
      let ordered = List.filter_map (fun name ->
        List.assoc_opt name ctx_by_name) args_names in
      List.rev ordered
    in
    let after_explicit, _ = Core.Ctxt.to_prod explicit_ctx core_ty in

    (* Find remaining free vars — these become implicit *)
    let free_vars = Api_lp.LibTerm.free_vars after_explicit in
    let implicit_ctx = List.filter (fun (v, _, _) ->
      Core.Term.VarSet.mem v free_vars) ctx in
    let ty, _ = Core.Ctxt.to_prod implicit_ctx after_explicit in
    let impl = List.map (fun _ -> true) implicit_ctx in

    let escaped_name = unique_name str in
    if replacements <> [] then
      Api_lp.register_explicit_replacements escaped_name replacements;
    let sym = add_constant ~impl escaped_name ty in
    { syms = [sym]; rules = []; }

  end else begin
    (* Has :args - need auxiliary symbol with rewrite rule *)

    (* Create context for encoding args - need all params *)
    let arg_ctx, _ = enc_params ps in

    (* Infer the type of each arg by encoding and using LambdaPi's type inference.
       We encode the arg term, then use Infer to get its type. *)
    let infer_arg_type arg =
      let encoded = enc_term ps arg_ctx arg |> resolve_term ~ctx:arg_ctx in
      let prob = Core.Term.new_problem () in
      match Core.Infer.infer_noexn prob arg_ctx encoded with
      | Some (_, ty) ->
        (* ty is the LambdaPi type (e.g., τ U). We want just U (the Set). *)
        (* If ty = τ X, extract X. Otherwise use ty as-is. *)
        un_tau ty
      | None ->
        (* Fallback: use a placeholder *)
        failf "Cannot infer type of arg: %s" (Pp_eo.term_str arg)
    in

    (* Find parameters used in premises/conclusion but not in args.
       These are "extra" params (e.g. :premise-list variables) that must
       be added as explicit arguments to _aux so they appear in the LHS. *)
    let args_syms = EO.symbols_in_terms args in
    let rhs_syms = EO.symbols_in_terms (prems @ [conc]) in
    let param_names = List.map (fun (n, _, _) -> n) ps in
    let extra_params = List.filter (fun (n, _, _) ->
      EO.Set.mem n rhs_syms &&
      not (EO.Set.mem n args_syms) &&
      List.mem n param_names
    ) ps in
    (* Filter out Type params — they become implicit, not extra args *)
    let extra_params = List.filter (fun (_, ty, _) ->
      ty <> EO.Symbol EO.Builtin.ty_type) extra_params in

    let extra_lp_types = List.map (fun (_, ty, _) ->
      enc_term ps arg_ctx ty |> resolve_term ~ctx:arg_ctx) extra_params in
    let all_args = args @ List.map (fun (n, _, _) -> EO.Symbol n) extra_params in
    let arg_lp_types = List.map infer_arg_type args in
    let all_lp_types = arg_lp_types @ extra_lp_types in

    (* Build the _aux symbol type: τ T1 → τ T2 → ... → TYPE *)
    let aux_body_ty =
      List.fold_right
        (fun arg_ty acc ->
           let ty_enc = tau_of arg_ty in
           mk_Prod (ty_enc, bind_var (new_var "_") acc))
        all_lp_types
        (mk_Type)
    in

    (* Find implicit type params for _aux *)
    let aux_free_vars = Api_lp.LibTerm.free_vars aux_body_ty in
    let aux_impl_ctx =
      List.filter (fun (v, _, _) -> Core.Term.VarSet.mem v aux_free_vars) arg_ctx
    in
    let aux_impl = List.map (fun _ -> true) aux_impl_ctx in
    let aux_ty, _ = Core.Ctxt.to_prod aux_impl_ctx aux_body_ty in

    let aux_name = unique_name (str ^ "_aux") in
    let aux_sym = add_sequential ~impl:aux_impl aux_name aux_ty in

    (* Build the rewrite rule for _aux.
       LHS: (aux_name arg1 arg2 ... extra1 extra2 ...)
       RHS: Proof prem1 → ... → Proof conclusion *)

    (* Build LHS as an Eunoia Apply term *)
    let lhs_eo = EO.Apply (aux_name, all_args) in

    (* For RHS, we need to encode it specially since Proof is not in Eunoia.
       We'll encode the premises and conclusion, then build the arrow. *)
    let enc t = t
      |> enc_term ps arg_ctx
      |> resolve_term ~debug:!verbose ~ctx:arg_ctx ~expected_ty:tau_bool
      |> bind_pvars arg_ctx arg_ctx
    in

    let prems_enc = List.map enc prems in
    let conc_enc = enc conc in
    let rhs = build_proof_arrow prems_enc conc_enc in

    (* For LHS, use enc_case's encoding pattern *)
    let l = lhs_eo
      |> enc_term ps arg_ctx
      |> resolve_term ~debug:!verbose ~ctx:arg_ctx
      |> strip_eo_as
      |> bind_pvars arg_ctx arg_ctx
    in
    let _, lhs_args = Core.Term.get_args l in

    let names = List.rev_map (fun (v, _, _) -> base_name v) arg_ctx |> Array.of_list in
    let vars_nb = List.length arg_ctx in

    let aux_rule : rule = {
      lhs = lhs_args;
      rhs;
      arity = List.length lhs_args;
      arities = Array.make vars_nb 0;
      vars_nb;
      xvars_nb = 0;
      names;
      rule_pos = None;
    } in

    (* Build the main symbol type:
       Π x1 : τ T1, ... Π xn : τ Tn, <name>_aux x1 ... xn *)

    (* Create fresh variables for the Π-bound args *)
    let arg_vars = List.mapi (fun i _ -> new_var (Printf.sprintf "x%d" (i + 1))) all_lp_types in

    (* Build _aux applied to implicit type params and then arg variables.
       Apply impl_ctx vars explicitly to avoid introducing placeholders. *)
    let aux_applied =
      let head =
        List.fold_left
          (fun acc (v, _, _) -> mk_Appl (acc, mk_Vari v))
          (mk_Symb aux_sym)
          (List.rev aux_impl_ctx)
      in
      List.fold_left
        (fun acc v -> mk_Appl (acc, mk_Vari v))
        head arg_vars
    in

    (* Build Π x1 : τ T1, ... Π xn : τ Tn, aux_applied *)
    let main_body_ty =
      List.fold_right2
        (fun arg_ty v acc ->
           let ty_enc = tau_of arg_ty in
           mk_Prod (ty_enc, bind_var v acc))
        all_lp_types arg_vars aux_applied
    in

    (* Find implicit type params for main symbol *)
    let main_free_vars = Api_lp.LibTerm.free_vars main_body_ty in
    let main_impl_ctx =
      List.filter (fun (v, _, _) -> Core.Term.VarSet.mem v main_free_vars) arg_ctx
    in
    let main_impl = List.map (fun _ -> true) main_impl_ctx in
    let main_ty, _ = Core.Ctxt.to_prod main_impl_ctx main_body_ty in

    let main_sym = add_constant ~impl:main_impl (unique_name str) main_ty in

    { syms = [aux_sym; main_sym];
      rules = [(aux_sym, aux_rule)]; }
  end

(* Encode an assume command.
   (assume s F) becomes: symbol s : Proof F; *)
let enc_assume str formula =
  let ctx = empty_ctxt in
  let tau_bool = tau_of (mk_Symb (find "Bool")) in
  let formula_enc = enc_term [] ctx formula |> resolve_term ~ctx ~expected_ty:tau_bool in
  let ty = mk_proof formula_enc in
  let sym = add_constant ~impl:[] (unique_name str) ty in
  { syms = [sym]; rules = []; }

(* Encode a step command.
   (step s F :rule r :premises (p1 ... pn) :args (a1 ... am))
   becomes: symbol s ≔ r a1 ... am p1 ... pn;
   Args precede premises to match the LP type signature produced by enc_rule. *)
let enc_step str rule_name premises args conc_opt =
  let ctx = empty_ctxt in
  let rule_sym = get_sym rule_name in
  let head = enc_sym rule_sym in
  (* Encode premises (which are proof term references) *)
  let prems_enc = List.map (fun p -> enc_term [] ctx p |> resolve_term ~debug:!verbose ~ctx) premises in
  (* Check if the rule has :premise-list — if so, fold premises into a
     single conjunction proof using proof_cons/proof_nil.
     E.g. premises [p1; p2] become:
       proof_cons p1 (proof_cons p2 proof_nil)
     which has type Proof (and F1 (and F2 true)).
     We also resolve the folded term with its expected Proof type
     to help LP's unifier solve implicits on the outer rule. *)
  let prems_enc, formula_enc =
    let rule_decl = Elab.find_all_eo_symbols rule_name
      |> List.find_map (fun (_, sym) ->
        match sym with EO.Rule (_, rdec) -> Some rdec | _ -> None)
    in
    match rule_decl with
    | Some { prem = Some (EO.PremiseList (_, op)); _ } ->
      let proof_nil_sym = get_sym "proof_nil" in
      let proof_cons_sym = get_sym "proof_cons" in
      (* Look up the operator's nil terminator *)
      let op_name = (match op with EO.Symbol s -> s | _ -> failf "premise-list op not a symbol") in
      let nil_term = match Elab.lookup_eo_symbol op_name with
        | Some (EO.Decl (_, _, Some (EO.RightAssocNil nil)))
        | Some (EO.Decl (_, _, Some (EO.RightAssocNilNSN nil))) -> nil
        | _ -> failf "premise-list op %s has no nil terminator" op_name
      in
      (* Build the conjunction formula from individual premise formulas.
         Each premise pi has type Proof(Fi); we infer Fi and fold:
         (op F1 (op F2 ... nil)) *)
      let op_enc = enc_term [] ctx op |> resolve_term ~debug:!verbose ~ctx in
      let nil_enc = enc_term [] ctx nil_term |> resolve_term ~debug:!verbose ~ctx in
      let premise_formulas = List.map (fun p ->
        (* Infer the type of each proof term to get the formula *)
        let prob = Core.Term.new_problem () in
        match Core.Infer.infer_noexn prob ctx p with
        | Some (_, ty) ->
          (* ty = Proof(F), extract F *)
          (match ty with
           | Core.Term.Appl (Core.Term.Symb s, f) when s.Core.Term.sym_name = "Proof" -> f
           | _ -> failf "premise type is not Proof(...)")
        | None -> failf "cannot infer premise type"
      ) prems_enc in
      (* Fold formulas: (op F1 (op F2 ... nil)) *)
      let folded_formula = List.fold_right (fun f acc ->
        hol_app (hol_app op_enc f) acc
      ) premise_formulas nil_enc in
      let folded_proof_ty = mk_proof folded_formula in
      (* Build the proof term: proof_cons p1 (proof_cons p2 ... proof_nil) *)
      let folded = List.fold_right (fun p acc ->
        add_args (enc_sym proof_cons_sym) [p; acc]
      ) prems_enc (enc_sym proof_nil_sym) in
      (* Resolve with expected type to fill in implicits *)
      let folded_resolved = resolve_term ~debug:!verbose ~ctx ~expected_ty:folded_proof_ty folded in
      ([folded_resolved], Some folded_formula)
    | _ -> (prems_enc, None)
  in
  (* Encode args *)
  let args_enc = List.map (fun a -> enc_term [] ctx a |> resolve_term ~debug:!verbose ~ctx) args in
  (* Build the full application.
     For :premise-list rules, the LP signature has the folded formula E
     as an explicit parameter (before :args and the proof). Insert it. *)
  let body_raw =
    let formula_args = match formula_enc with
      | Some f -> [f]
      | None -> []
    in
    let all_args = formula_args @ args_enc @ prems_enc in
    List.fold_left (fun acc arg -> mk_Appl (acc, arg)) head all_args
  in
  (* Resolve body, using conclusion as hint for implicit resolution if available.
     Use the conclusion as the definition's type annotation so that downstream
     steps can infer premise types via infer_noexn.
     However, some CPC programs (e.g. $resolve) produce terms whose normal
     forms differ structurally from the Eunoia conclusion (or-nil=false vs
     and-nil=true), causing unification failures at lambdapi check time.
     For those cases we still set the annotation on the internal LP symbol
     (so infer_noexn works) but suppress it in the printed .lp file. *)
  let body, expected_ty, print_ty = match conc_opt with
    | Some conc ->
      let conc_enc = enc_term [] ctx conc |> resolve_term ~debug:!verbose ~ctx in
      let exp_ty = mk_proof conc_enc in
      let body_resolved = resolve_term ~debug:!verbose ~ctx ~expected_ty:exp_ty body_raw in
      (* Check if the resolved body type-checks against the expected type.
         If not, suppress the annotation in the printed file but keep it
         on the internal symbol so infer_noexn still returns Proof(F). *)
      let prob = Core.Term.new_problem () in
      let ok = match Core.Infer.check_noexn prob ctx body_resolved exp_ty with
        | Some _ -> Core.Unif.solve_noexn prob
        | None -> false
      in
      (body_resolved, Some exp_ty, ok)
    | None ->
      (resolve_term ~debug:!verbose ~ctx body_raw, None, true)
  in
  let sym = add_definition ~impl:[] ~print_ty (unique_name str) expected_ty body in
  { syms = [sym]; rules = []; }

let enc_symbol name = function
  | EO.Decl (ps, ty, attr) ->
    enc_decl name ps ty attr
  | EO.Defn (ps, body, ty_opt) ->
    enc_defn name ps body ty_opt
  | EO.Prog (ps, doms, ran, cases) ->
    enc_prog name ps doms ran cases
  | EO.Ltrl (cat, ty) ->
    enc_ltrl cat ty
  | EO.Rule (ps, rdec) ->
    enc_rule name ps rdec
  | EO.Assume formula ->
    enc_assume name formula
  | EO.AssumePush formula ->
    push_assumption formula;
    enc_assume name formula
  | EO.Step (rule_name, premises, args, conc_opt) ->
    enc_step name rule_name premises args conc_opt
  | EO.StepPop (rule_name, premises, args, conc_opt) ->
    let assm_formula = pop_assumption () in
    (* The assumption is now an explicit parameter in the rule's LP type,
       so pass it as the first arg (before :args) *)
    enc_step name rule_name premises (assm_formula :: args) conc_opt

(* Encode a single named symbol. Caller is responsible for
   calling reset_overloads() once before the first symbol in a module. *)
let enc_one (name : string) (sym : EO.symbol) : enc_result =
  set_current_symbol name;
  set_current_phase "encode";
  let r = enc_symbol name sym in
  set_current_symbol "";
  set_current_phase "";
  r
